version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /src/Eudiplo.Client.Sample.AccessControl/Frontend
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /src/Eudiplo.Client.Sample.AccessControl/Backend
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
